[build]
  base = "beta_testing_platform_code/beta-testing-frontend/"
  publish = "beta_testing_platform_code/beta-testing-frontend/dist/"
  command = "pnpm install && pnpm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
