[build]
  base = "."
  publish = "dist/"
  command = "pnpm install && pnpm run build"

# Headers for better caching and security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
